export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED";
export const ADD_USER_SUCCEEDED = "ADD_USER_SUCCEEDED";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const REMOVE_USER = "REMOVE_USER";
export const ADD_LIST_REQUESTED = "ADD_LIST_REQUESTED";
export const ADD_LIST_SUCCEEDED = "ADD_LIST_SUCCEEDED";
export const ADD_LIST_FAILED = "ADD_LIST_FAILED";
