export const ADD_USER_REQUESTED = "ADD_USER_REQUESTED ";
export const ADD_USER_SUCCEEDED = "ADD_USER_SUCCEEDED";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const REMOVE_USER = "REMOVE_USER";
